<a href="https://colab.research.google.com/github/alexbrunoliveira/Introdu-ao-ao-DataScience/blob/main/Organizando_DtaFrames_(Sort).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
list('321')

['3', '2', '1']

In [ ]:
df = pd.DataFrame(data, list('321'), list('ZYX'))
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [ ]:
df.sort_index(inplace = True)

In [ ]:
df.sort_index(inplace = True, axis = 1)
df

   X  Y  Z
1  9  8  7
2  6  5  4
3  3  2  1

In [ ]:
df.sort_values(by = 'X', inplace = True)
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [ ]:
df.sort_values(by = ['X','Y'], inplace = True)
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [ ]:
df.sort_values(by = '3', axis = 1, inplace = True)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

#### Exercício

In [ ]:
df.sort_index()
df.sort_index(axis = 1)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9